#############################################################################
# Makefile for building: mip_app
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  mip_app.pro
# Template: app
# Command: F:\software\Qt5.7.0\5.7\msvc2013_64\bin\qmake.exe -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile mip_app.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = F:\software\Qt5.7.0\5.7\msvc2013_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: mip_app.pro ..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf ..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\spec_pre.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\common\angle.conf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\common\msvc-base.conf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\common\msvc-desktop.conf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\qconfig.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_location.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_script.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qt_functions.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qt_config.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\qt_config.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\default_pre.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\resolve_config.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\default_post.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qml_debug.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\rtti.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\precompile_header.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\warn_on.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qt.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\resources.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\moc.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\opengl.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\uic.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\file_copies.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\windows.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\testcase_targets.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\exceptions.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\yacc.prf \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\lex.prf \
		mip_app.pro \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\qtmaind.prl \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Widgets.prl \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Gui.prl \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Network.prl \
		..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Core.prl
	$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile mip_app.pro
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\spec_pre.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\common\angle.conf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\common\msvc-base.conf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\common\msvc-desktop.conf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\qconfig.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_location.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_purchasing.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_script.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webview.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qt_functions.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qt_config.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\qt_config.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\exclusive_builds.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\default_pre.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\default_pre.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\resolve_config.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\default_post.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qml_debug.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\rtti.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\precompile_header.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\warn_on.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\qt.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\resources.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\moc.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\opengl.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\uic.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\file_copies.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\win32\windows.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\testcase_targets.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\exceptions.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\yacc.prf:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\mkspecs\features\lex.prf:
mip_app.pro:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\qtmaind.prl:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Widgets.prl:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Gui.prl:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Network.prl:
..\..\..\software\Qt5.7.0\5.7\msvc2013_64\lib\Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile mip_app.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) mip_app.exp
	-$(DEL_FILE) mip_app.ilk
	-$(DEL_FILE) mip_app.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash mip_app.lib mip_app.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
